CREATE TABLE IF NOT EXISTS "plataforma-niej_psychology_triage" (
	"id" varchar(256) PRIMARY KEY NOT NULL,
	"resident_id" varchar(256) NOT NULL,
	"project_id" varchar(256) NOT NULL,
	"leisure_opportunities_evaluation" varchar(256),
	"sleep_evaluation" varchar(256),
	"diet_evaluation" varchar(256),
	"physical_activity" varchar(256),
	"routine_description" varchar(256),
	"personal_time_well_being" varchar(256),
	"current_feelings" varchar(256),
	"support_system" varchar(256),
	"current_feeling_description" varchar(256),
	"stress_level" varchar(256),
	"stress_coping" varchar(256),
	"nervousness_frequency" varchar(256),
	"sadness_frequency" varchar(256),
	"psychological_care" varchar(256),
	"psychiatric_care" varchar(256),
	"psychiatric_medication_use" varchar(256),
	"voluntary_psychological_care" varchar(256),
	"interaction_observations" varchar(256),
	"psychology_team_guidance" varchar(256),
	"community_suggestions" varchar(256),
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp
);
