CREATE TABLE IF NOT EXISTS "plataforma-niej_law" (
	"id" varchar(256) PRIMARY KEY NOT NULL,
	"resident_id" varchar(256) NOT NULL,
	"project_id" varchar(256) NOT NULL,
	"birth_registration" varchar(256),
	"assistencial_benefits" varchar(256),
	"benefits_details" varchar(256),
	"retirement" varchar(256),
	"Pension" varchar(256),
	"pension_details" varchar(256),
	"alimentic_pension" varchar(256),
	"alimentic_pension_details" varchar(256),
	"imovel_or_terrain_regulantion" varchar(256),
	"imovel_or_terrain_regulantion_details" varchar(256),
	"juducial_alvara" varchar(256),
	"extra_judicial_agreement" varchar(256),
	"executiv_title" varchar(256),
	"paternity_recognition" varchar(256),
	"paternity_contestation" varchar(256),
	"child_custody" varchar(256),
	"divorce" varchar(256),
	"stable_union" varchar(256),
	"guardianship_or_curatorship" varchar(256),
	"undue_charge" varchar(256),
	"undue_charge_details" varchar(256),
	"documents_emission" varchar(256),
	"others" text,
	"children_involved" varchar(256),
	"elderly_involved" varchar(256),
	"pcd_involved" varchar(256),
	"urgency" text,
	"documents_or_evidences" text,
	"previous_legal_guidance" varchar(256),
	"public_defense" varchar(256),
	"police_station" varchar(256),
	"goverment_secretary" varchar(256),
	"cras_access" varchar(256),
	"caduni_tel_number" varchar(256),
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp
);
