CREATE TABLE IF NOT EXISTS "plataforma-niej_dental_evaluation" (
	"id" varchar(256) PRIMARY KEY NOT NULL,
	"resident_id" varchar(256) NOT NULL,
	"project_id" varchar(256) NOT NULL,
	"general_complaint" text,
	"tooth_pain" text,
	"gum_pain" text,
	"bleeding_gums" text,
	"uses_dental_floss" text,
	"uses_toothpaste" text,
	"brushing_frequency" text,
	"toothbrush_type" text,
	"toothbrush_replacement" text,
	"uses_pacifier" text,
	"has_allergy" text,
	"allergy_details" text,
	"dental_treatment_status" text,
	"dental_treatment_notes" text,
	"takes_medication" text,
	"medication_details" text,
	"has_other_illness" text,
	"illness_details" text,
	"gum_status" text,
	"gum_notes" text,
	"buccal_mucosa_status" text,
	"buccal_mucosa_notes" text,
	"palate_status" text,
	"palate_notes" text,
	"floor_of_mouth_status" text,
	"floor_of_mouth_notes" text,
	"tongue_status" text,
	"tongue_notes" text,
	"fluorosis_status" text,
	"fluorosis_notes" text,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp
);
