ALTER TABLE "plataforma-niej_law" ADD COLUMN "birth_registration" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "assistencial_benefits" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "benefits_details" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "retirement" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "Pension" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "pension_details" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "alimentic_pension" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "alimentic_pension_details" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "imovel_or_terrain_regulantion" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "imovel_or_terrain_regulantion_details" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "juducial_alvara" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "extra_judicial_agreement" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "executiv_title" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "paternity_recognition" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "paternity_contestation" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "child_custody" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "divorce" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "stable_union" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "guardianship_or_curatorship" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "undue_charge" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "undue_charge_details" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "documents_emission" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "others" text;--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "children_involved" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "elderly_involved" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "pcd_involved" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "urgency" text;--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "documents_or_evidences" text;--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "previous_legal_guidance" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "public_defense" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "police_station" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "goverment_secretary" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "cras_access" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" ADD COLUMN "caduni_tel_number" varchar(256);--> statement-breakpoint
ALTER TABLE "plataforma-niej_nutrition_screening" ADD COLUMN "rcq" text;--> statement-breakpoint
ALTER TABLE "plataforma-niej_nutrition_screening" ADD COLUMN "weight_loss" text;--> statement-breakpoint
ALTER TABLE "plataforma-niej_nutrition_screening" ADD COLUMN "serius_or_discomfort" text;--> statement-breakpoint
ALTER TABLE "plataforma-niej_law" DROP COLUMN IF EXISTS "message";